name: build-sphinx-to-gh-pages

env:
  GITHUB_ACTOR: petersonwsantos
  GITHUB_REPOSITORY: petersonwsantos/resumo-aws
  GITHUB_TOKEN: ${{ secrets.GIT_WFW1 }}

on: 
  push:
    branches: [ main ]

jobs:

  build_sphinx_job:
    runs-on: ubuntu-20.04
    container: debian:buster-slim

    steps:
    
      - name: Get prerequisites and clone repository
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_WFW1 }}
        run: |
          set -x
          apt-get update
          apt-get install -y git
          git clone "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
        shell: bash

      - name: Run build script for Sphinx pages
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_WFW1 }}
        run: "docs/buildsite.sh"
        shell: bash
